version: '3.7'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    restart: unless-stopped 
    ports:
      - 5050:8080

